name: 'Upload mitmproxy artifacts'
description: 'Prepare mitmproxy traffic files for artifact upload'

inputs:
  enabled:
    description: 'Whether mitmproxy was enabled'
    required: false
    default: 'true'
  passphrase:
    description: 'Passphrase for artifact encryption'
    required: true
  traffic-file:
    description: 'Path to traffic file (optional, will auto-detect if not provided)'
    required: false

outputs:
  artifact-path:
    description: 'Path to prepared artifacts'
    value: ${{ steps.upload.outputs.artifact-path }}

runs:
  using: 'composite'
  steps:
    - name: Prepare artifacts
      id: upload
      shell: bash
      run: |
        ${{ github.action_path }}/../scripts/upload-artifacts.sh
        echo "artifact-path=${GITHUB_WORKSPACE}/mitmproxy-traffic/artifacts" >> $GITHUB_OUTPUT
      env:
        INPUT_ENABLED: ${{ inputs.enabled }}
        INPUT_PASSPHRASE: ${{ inputs.passphrase }}
        INPUT_TRAFFIC_FILE: ${{ inputs.traffic-file }}