name: Example usage of mitmproxy-logger-action

on:
  push:
  pull_request:

jobs:
  test-with-mitmproxy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      # Start mitmproxy logging
      - name: Start mitmproxy
        id: mitmproxy
        uses: yaegashi/mitmproxy-logger-action@v1
        with:
          enabled: true
          listen-host: '127.0.0.1'
          listen-port: '8080'
          install-cacert: true
          set-envvars: true
          passphrase: ${{ secrets.MITMPROXY_PASSPHRASE }}
      
      # Configure your application to use the proxy
      - name: Run tests with proxy
        run: |
          # With set-envvars: true (default), environment variables are automatically set
          # You can still override them if needed:
          # export http_proxy=${{ steps.mitmproxy.outputs.proxy-url }}
          # export https_proxy=${{ steps.mitmproxy.outputs.proxy-url }}
          
          # Example: test HTTP requests
          curl http://httpbin.org/get
          curl https://httpbin.org/get
          
          # Your actual test commands would go here
          # npm test
          # python -m pytest
          # etc.
      
      # mitmproxy will automatically stop and upload artifacts when the job completes