name: Example usage of mitmproxy-logger-action

on:
  push:
  pull_request:

jobs:
  test-with-mitmproxy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      # Start mitmproxy logging
      - name: Start mitmproxy
        id: mitmproxy
        uses: yaegashi/mitmproxy-logger-action@main
        with:
          enabled: true
          version: '12.1.1'  # Specify mitmproxy version
          listen-host: '127.0.0.1'
          listen-port: '8080'
          install-cacert: true
          set-envvars: true
          passphrase: ${{ secrets.MITMPROXY_PASSPHRASE }}
      
      # Test HTTP requests with proxy - verbose output to see proxy in action
      - name: Test HTTP requests
        id: test-http
        run: |
          # With set-envvars: true, proxy environment variables are automatically set
          # The -v flag provides verbose output to show the proxy connection
          curl -v "http://httpbin.org/get?id=test-http"
          curl -v "https://httpbin.org/get?id=test-http"
          
          # Your actual test commands would go here
          # npm test
          # python -m pytest
          # etc.
      
      # mitmproxy will automatically stop and upload artifacts when the job completes