name: Test mitmproxy-logger-action

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Start mitmproxy
        id: mitmproxy
        uses: ./
        with:
          enabled: true
          listen-host: '127.0.0.1'
          listen-port: '8080'
          passphrase: 'test-passphrase-123'
      
      - name: Test proxy is running
        run: |
          echo "Proxy URL: ${{ steps.mitmproxy.outputs.proxy-url }}"
          echo "Traffic file: ${{ steps.mitmproxy.outputs.traffic-file }}"
          
          # Test if the proxy is responding
          curl -x ${{ steps.mitmproxy.outputs.proxy-url }} --max-time 10 http://httpbin.org/get || true
          
          # Give some time for traffic to be logged
          sleep 2
      
      - name: Stop mitmproxy
        if: always()
        uses: ./stop
        with:
          enabled: true
      
      - name: Prepare traffic artifacts
        if: always()
        id: artifacts
        uses: ./upload
        with:
          enabled: true
          passphrase: 'test-passphrase-123'
          traffic-file: ${{ steps.mitmproxy.outputs.traffic-file }}
      
      - name: Upload artifacts to GitHub
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mitmproxy-traffic-test
          path: ${{ steps.artifacts.outputs.artifact-path }}